### ISSUE TITLE
Improve datagit documentation

### ISSUE THREAD

**Issue by Lucasdvrs** [data-drift/data-drift#174]
# Why we need this
Datagit document needs to be improved for faster & smoother installation

# Task
- [ ] Add [PyGithub import](https://pygithub.readthedocs.io/en/stable/introduction.html)
- [ ] Add auto_merge drift in the documentation. Auto_merge should be by default in the store_metric function
- [ ] Add step to authorize your datadrift app in your notion page
- [ ] Remove date_column in the notion config json
- [ ] Add to round numbers as a best practice when setting up your query
- [ ] Add lineage to the documentation
